apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  containers:
  - name: main
    image:  ubuntu
    command: ['sleep', '999999']
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 100m
        memory: 4Mi
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
